### ISSUE TITLE
Migrate away from bower...

### ISSUE THREAD

**Issue by the-t-in-rtf** [fluid-lab/music-ctrls#118]
The postinstall step fails for me frequently with errors like:

> > sisiliano@1.0.0 postinstall /Users/duhrer/Source/lpiano/node_modules/sisiliano
> > node node_modules/bower/bin/bower install && grunt build
> 
> module.js:471
>     throw err;
>     ^
> 
> Error: Cannot find module '/Users/duhrer/Source/lpiano/node_modules/sisiliano/node_modules/bower/bin/bower'
>     at Function.Module._resolveFilename (module.js:469:15)
>     at Function.Module._load (module.js:417:25)
>     at Module.runMain (module.js:604:10)
>     at run (bootstrap_node.js:394:7)
>     at startup (bootstrap_node.js:149:9)
>     at bootstrap_node.js:509:3

It seems like a good time to migrate away from using two package managers, and to just use npm for everything.   I'm happy to prepare a PR that does this.

**Comment by dinukadesilva** [comment]
Sure @the-t-in-rtf ......... you are welcome.... 
It's better to have one package manager...
